FROM python:3.10

RUN pip install --upgrade pip && \
    pip install mlflow psycopg2-binary boto3

EXPOSE 5000

ENV BACKEND_URI sqlite:///mydb.sqlite
ENV ARTIFACT_ROOT s3://mlflow-artifact-store

CMD mlflow server --backend-store-uri ${BACKEND_URI} --default-artifact-root ${ARTIFACT_ROOT} --host 0.0.0.0 --port 5000